USE ScrumLeaderboard;
GO

CREATE TABLE dbo.BoardItem
(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ItemType VARCHAR(MAX) NOT NULL,
	Title VARCHAR(MAX) NOT NULL,
	Description VARCHAR(MAX) NOT NULL,
	State VARCHAR(MAX) NOT NULL,
	Priority VARCHAR(MAX) NOT NULL,
	Effort VARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_BoardItem PRIMARY KEY CLUSTERED (ID)

)

