USE ScrumLeaderboard;
GO

CREATE TABLE dbo.Project
(
	ID INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(MAX) NOT NULL,
	Description VARCHAR(MAX) NOT NULL,
	Creator VARCHAR(MAX) NOT NULL,
	CreateDate DATETIME2 NOT NULL,

	CONSTRAINT PK_Project PRIMARY KEY CLUSTERED (ID)

);

CREATE TABLE dbo.ProjectAccess
(
	ID INT IDENTITY(1,1) NOT NULL,
	ProjectID INT NOT NULL,
	UserID INT NOT NULL,
	AccessLevel VARCHAR(MAX) NOT NULL,

	CONSTRAINT PK_ProjectAccess PRIMARY KEY CLUSTERED (ID)

);

CREATE TABLE dbo."User"
(
	ID INT IDENTITY(1,1) NOT NULL,
	UserName VARCHAR(30) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	CreateDate DATETIME2 NOT NULL,

	CONSTRAINT PK_User PRIMARY KEY CLUSTERED (ID)

);